name: Bug Report
description: An issue (or bug) with the software.
labels:
  - unconfirmed

body:
  - type: markdown
    attributes:
      value: |
        Please make sure to confirm any bug reports in the [Discord server](https://discord.com/invite/nDxrPWh8pk) as well as search in this repository for any existing issues similar to yours before submitting a report.

  - type: textarea
    attributes:
      label: Current Behavior
      description: Tell us what the issue is, be as clear and detailed as possible.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: Tell us what you expect to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproducing
      description: Tell us how to reproduce the bug, be as detailed as possible.
    validations:
      required: true

  - type: input
    attributes:
      label: Dashactyl Version
      description: The specific Dashactyl version you are using (not latest or development).
    validations:
      required: true

  - type: input
    attributes:
      label: Panel Version
      description: The specific Pterodactyl Panel version you are using (not latest or development).
    validations:
      required: true

  - type: input
    attributes:
      label: Logs
      description: Include any console logs you have (if applicable) in the form of a **link** (using hastebin or similar).
    validations:
      required: true
